In [4]:
import numpy as np
import pandas as pd

In [6]:
[1, 2, 3]

[1, 2, 3]

In [7]:
[[1, 2, 3],[4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [8]:
a = np.array([1, 2, 3])
print('a: ', a)

a:  [1 2 3]


In [10]:
b = np.array([[1,2,3],[4, 5, 6]])
print('b: ', b)

b:  [[1 2 3]
 [4 5 6]]


In [12]:
# a
print('a = ')
print(a)
print('a ndim{}'.format(a.ndim))
print('a shape {}'.format(a.shape))
print('a size {}'.format(a.size))
print('a dtype {}'.format(a.dtype))
print('a itemsize {}'.format(a.itemsize))

a = 
[1 2 3]
a ndim1
a shape (3,)
a size 3
a dtype int64
a itemsize 8


In [13]:
# b
print('b = ')
print(b)
print('b ndim{}'.format(b.ndim))
print('b shape {}'.format(b.shape))
print('b size {}'.format(b.size))
print('b dtype {}'.format(b.dtype))
print('b itemsize {}'.format(b.itemsize))

b = 
[[1 2 3]
 [4 5 6]]
b ndim2
b shape (2, 3)
b size 6
b dtype int64
b itemsize 8


In [16]:
C = np.array([[1, 2],[3,4]], dtype = complex)
print(C)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [17]:
a = np.zeros((2,3))
print('np.zeros((2,3))= \n{}\n'.format(a))

np.zeros((2,3))= 
[[0. 0. 0.]
 [0. 0. 0.]]



In [19]:
b = np.ones((2,3))
print('np.ones((2,3))= \n{}\n'.format(b))

np.ones((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]



In [22]:
c = np.empty((2,3))
print('np.empty((2,3))= \n{}\n'.format(c))

np.empty((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]



In [26]:
d = np.arange(1, 2, 0.3)
print('np.arange(1, 2, 0.3)= \n{}\n'.format(d))

np.arange(1, 2, 0.3)= 
[1.  1.3 1.6 1.9]



In [27]:
e = np.linspace(1, 2, 7)
print('np.linspace(1, 2, 7)= \n{}\n'.format(e))

np.linspace(1, 2, 7)= 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]



In [30]:
f = np. random. random((2,3))
print('np.random.random((2,3))= \n{}\n'.format(f))

np.random.random((2,3))= 
[[0.88658075 0.35609693 0.99069705]
 [0.51050979 0.33817105 0.41800037]]



## shape and operation

In [31]:
zero_line = np.zeros((1,3))
one_column = np.ones((3,1))
print('zero_line = \n{}\n'.format(zero_line))
print('one_column= \n{}\n'.format(one_column))

zero_line = 
[[0. 0. 0.]]

one_column= 
[[1.]
 [1.]
 [1.]]



In [32]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.arange(11, 20)
print('a = \n{}\n'.format(a))
print('b = \n{}\n'.format(b))

a = 
[[1 2 3]
 [4 5 6]]

b = 
[11 12 13 14 15 16 17 18 19]



In [33]:
b = b.reshape(3, -1)
print('b.reshape(3, -1)= \n{}\n'.format(b))

b.reshape(3, -1)= 
[[11 12 13]
 [14 15 16]
 [17 18 19]]



In [34]:
test = np.arange(1, 21)
test1 = test.reshape(2,-1)
print(test1)
test2 = test.reshape(4, -1)
print(test2)
test3 = test.reshape(5, 4)
print(test3)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [35]:
c = np.vstack((a, b, zero_line))
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]


In [36]:
a = a.reshape(3,2)
d = np.hstack((a, b, one_column))
print(d)

[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]


In [38]:
e= np.hsplit(d, 3)
print(e)
print(e[1])

[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]
[[11. 12.]
 [14. 15.]
 [17. 18.]]


In [39]:
f = np.hsplit(d, (1,3))
print(f)

[array([[1.],
       [3.],
       [5.]]), array([[ 2., 11.],
       [ 4., 14.],
       [ 6., 17.]]), array([[12., 13.,  1.],
       [15., 16.,  1.],
       [18., 19.,  1.]])]


In [40]:
g = np.vsplit(d, 3)
print(g)

[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]


In [41]:
print(g[0])

[[ 1.  2. 11. 12. 13.  1.]]
